name: exchange_rate_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.0.7+4
  flutter_mobx: ^2.0.6
  go_router: ^6.0.3
  dio: ^5.4.3+1
  google_fonts: ^4.0.4
  get_it: ^7.7.0
  flutter_secure_storage: ^4.2.1
  flutter_animate: ^4.5.0
  chips_choice: ^3.0.1
  get_storage: ^2.1.1
  decimal: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.1.7
  mobx_codegen: ^2.0.4
  mockito: ^5.4.4

flutter:
  uses-material-design: true